// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocksOA

import (
	models "WeatherProject/models"

	mock "github.com/stretchr/testify/mock"
)

// MockWeatherRepository is an autogenerated mock type for the WeatherRepository type
type MockWeatherRepository struct {
	mock.Mock
}

// FindAll provides a mock function with no fields
func (_m *MockWeatherRepository) FindAll() ([]models.WeatherResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.WeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.WeatherResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.WeatherResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByDate provides a mock function with given fields: date
func (_m *MockWeatherRepository) FindByDate(date string) (*models.WeatherResponse, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FindByDate")
	}

	var r0 *models.WeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.WeatherResponse, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(string) *models.WeatherResponse); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: w
func (_m *MockWeatherRepository) Insert(w models.WeatherResponse) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.WeatherResponse) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWeatherRepository creates a new instance of MockWeatherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherRepository {
	mock := &MockWeatherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
