// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocksOA

import (
	models "WeatherProject/src/models"

	mock "github.com/stretchr/testify/mock"
)

// WeatherServiceInterface is an autogenerated mock type for the WeatherServiceInterface type
type WeatherServiceInterface struct {
	mock.Mock
}

// CreateWeatherEntry provides a mock function with given fields: locale, msg
func (_m *WeatherServiceInterface) CreateWeatherEntry(locale string, msg string) error {
	ret := _m.Called(locale, msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateWeatherEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(locale, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllWeather provides a mock function with no fields
func (_m *WeatherServiceInterface) GetAllWeather() ([]models.WeatherResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllWeather")
	}

	var r0 []models.WeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.WeatherResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.WeatherResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemperature provides a mock function with no fields
func (_m *WeatherServiceInterface) GetTemperature() (*models.WeatherResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTemperature")
	}

	var r0 *models.WeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.WeatherResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.WeatherResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodayWeather provides a mock function with no fields
func (_m *WeatherServiceInterface) GetTodayWeather() (*models.WeatherResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTodayWeather")
	}

	var r0 *models.WeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.WeatherResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.WeatherResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWeatherServiceInterface creates a new instance of WeatherServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherServiceInterface {
	mock := &WeatherServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
